name: Update translations

on:
    schedule:
        - cron: "*/15 * * * *"
    workflow_dispatch:

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    translate:
        runs-on: ubuntu-latest
        steps:
            - name: Install po4a
              run: |
                  git -C $HOME clone --single-branch --recurse-submodules --shallow-submodules --no-tags --depth=1 https://github.com/mquinson/po4a
                  mkdir -p $HOME/.local/bin
                  echo '#!/bin/bash
                  PERLLIB='"$HOME"'/po4a/lib '"$HOME"'/po4a/po4a "$@"' > $HOME/.local/bin/po4a
                  chmod +x $HOME/.local/bin/po4a
                  sudo apt install -y liblocale-gettext-perl libtext-wrapi18n-perl libunicode-linebreak-perl libtest-pod-perl libyaml-tiny-perl cpanminus gettext libsgmls-perl
                  cpanm Locale::gettext http://search.cpan.org/CPAN/authors/id/R/RA/RAAB/SGMLSpm-1.1.tar.gz Text::WrapI18N Unicode::GCString YAML::Tiny
                  cpanm -v --installdeps --notest $HOME/po4a
            - name: Fetch source files
              run:  |
                  mkdir $HOME/repos
                  curl -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/LibreScore/repos?per_page=100" | grep -e 'git_url*' | cut -d \" -f 4 | sed -e 's/^git:\/\//https:\/\/${{ secrets.LIBRESCORE_USER }}:${{ secrets.LIBRESCORE_TOKEN }}@/g' | xargs -I {} bash -c "if [[ {} =~ /(docs|dl-librescore|app-librescore|webmscore-pwa).git$ ]]; then git -C $HOME/repos clone {} --single-branch --no-tags --depth=1 ; fi"
                  rm -R -f $HOME/repos/*/docs
                  rm -R -f $HOME/repos/docs/i18n
                  mv -f $HOME/repos/docs/source/titles $HOME/repos/titles
                  rm -R -f $HOME/repos/docs/source
                  find $HOME/repos -not -path "$HOME/repos/titles/*" ! -name "*.md" -type f -delete
                  find $HOME/repos -not -path "$HOME/repos/titles/*" -type d -empty -delete
            - uses: actions/checkout@v3
            - name: Generate translations
              run: |
                  rm -R -f source/*
                  mv -f $HOME/repos/* source/
                  rm -R -f $HOME/repos
                  /bin/bash ./po4a.sh
            - name: Push to current repo
              run: |
                  updated=0
                  mkdir -p ./docs
                  rm -R -f ./docs/*
                  cp -a ./i18n/docs/* ./docs/ -v
                  cp -a ./i18n/docs/en/* . -v
                  if [[ -n $(git status -z --porcelain ./i18n) ]]; then
                      updated=1
                      git config user.name github-actions
                      git config user.email github-actions@github.com
                      git add -A
                      git commit -m "chore: update translations"
                      git push
                  fi
            - name: Push to remote repos
              run: |
                  shopt -s nullglob
                  for dir in i18n/*/ ; do
                      dir=${dir%/}
                      repo=${dir#*/}
                      repo=${repo%/}
                      if ! [[ $repo =~ ^(docs|titles)$ ]]; then
                          git -C $HOME clone --single-branch --no-tags --depth=1 https://${{ secrets.LIBRESCORE_USER }}:${{ secrets.LIBRESCORE_TOKEN }}@github.com/LibreScore/$repo
                          mkdir -p $HOME/$repo/docs
                          rm -R -f $HOME/$repo/docs/*
                          cp -a $dir/* $HOME/$repo/docs/ -v
                          cp -a $dir/en/* $HOME/$repo/ -v
                          cd $HOME/$repo
                          if [[ -n $(git status -z --porcelain) ]]; then
                              updated=1
                              git config user.name github-actions
                              git config user.email github-actions@github.com
                              git add -A
                              git commit -m "chore: update translations"
                              git push
                          fi
                          cd $GITHUB_WORKSPACE
                      fi
                  done
                  shopt -u nullglob
                  if [[ $updated -eq 0 ]]; then
                      curl -i -u ${{ secrets.LIBRESCORE_USER }}:${{ secrets.LIBRESCORE_TOKEN }} -d '{"event_type":"delete_action","client_payload":{"run_id":"'"${{ github.run_id }}"'","repo":"LibreScore/docs"}}' -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/LibreScore/actions/dispatches
                  fi
