name: Update translations

on:
    schedule:
        - cron: "*/15 * * * *"
    workflow_dispatch:

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    translate:
        runs-on: ubuntu-latest
        steps:
            - name: Install po4a
              run: |
                  git -C $HOME clone --single-branch --recurse-submodules --shallow-submodules --no-tags --depth=1 https://github.com/mquinson/po4a
                  mkdir -p $HOME/.local/bin
                  echo '#!/bin/bash
                  PERLLIB='"$HOME"'/po4a/lib '"$HOME"'/po4a/po4a "$@"' > $HOME/.local/bin/po4a
                  chmod +x $HOME/.local/bin/po4a
                  sudo apt install -y liblocale-gettext-perl libtext-wrapi18n-perl libunicode-linebreak-perl libtest-pod-perl libyaml-tiny-perl cpanminus gettext libsgmls-perl
                  cpanm Locale::gettext http://search.cpan.org/CPAN/authors/id/R/RA/RAAB/SGMLSpm-1.1.tar.gz Text::WrapI18N Unicode::GCString YAML::Tiny
                  cpanm -v --installdeps --notest $HOME/po4a
            - name: Fetch source files
              run:  |
                  mkdir $HOME/repos
                  curl -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/LibreScore/repos?per_page=100" | grep -e 'git_url*' | cut -d \" -f 4 | sed -e 's/^git:\/\//https:\/\/PeterNjeim:${{ secrets.LIBRESCORE_TOKEN }}@/g' | xargs -I {} bash -c "if [[ {} =~ /(docs|dl-librescore|app-librescore|webmscore-pwa).git$ ]]; then git -C $HOME/repos clone {} --single-branch --no-tags --depth=1 ; fi"
                  rm -R -f $HOME/repos/*/docs
                  find $HOME/repos/docs/source -name "*.md" -type f -delete
                  find $HOME/repos/docs/source -type d -empty -delete
                  find $HOME/repos ! -name "*.md" -type f -delete
                  find $HOME/repos -type d -empty -delete
            - uses: actions/checkout@v3
            - name: Generate translations
              run: |
                  rm -R -f source/*
                  cp -a $HOME/repos/* source/ -v
                  rm -R -f $HOME/repos
                  /bin/bash ./po4a.sh
            - name: Push to current repo
              run: |
                  if [[ -n $(git status -z --porcelain ./i18n) ]]; then
                      mv -f ./i18n ../i18n
                      git config user.name github-actions
                      git config user.email github-actions@github.com
                      git add -A
                      if [[ -n $(git status -z --porcelain) ]]; then
                          git commit -m "chore: update translations"
                          git push
                      fi
                      mv -f ../i18n ./i18n
                  fi
            - name: Push to remote repos
              run: |
                  shopt -s nullglob
                  for dir in i18n/*/ ; do
                      dir=${dir%/}
                      repo=${dir#*/}
                      repo=${repo%/}
                      if ! [[ $repo =~ ^(docs|titles)$ ]]; then
                          git -C $HOME clone --single-branch --no-tags --depth=1 https://PeterNjeim:${{ secrets.LIBRESCORE_TOKEN }}@github.com/LibreScore/$repo
                          mkdir -p $HOME/$repo/docs
                          cp -a $dir/* $HOME/$repo/docs/ -v
                          cp -a $dir/en/* $HOME/$repo/ -v
                          cd $HOME/$repo
                          git config user.name github-actions
                          git config user.email github-actions@github.com
                          git add -A
                          echo "$(git status -z --porcelain)"
                          if [[ -n $(git status -z --porcelain) ]]; then
                              git commit -m "chore: update translations"
                              git push
                          fi
                          cd $GITHUB_WORKSPACE
                          rm -R -f $HOME/$repo
                      fi
                  done
                  shopt -u nullglob
