name: Update translations

on:
    push:
        branches: [master]
        paths:
            - "source/**"
    pull_request:
        branches: [master]
        paths:
            - "source/**"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install po4a
              run: |
                  git clone --depth 1 https://github.com/mquinson/po4a $HOME/po4a
                  mkdir -p $HOME/.local/bin
                  echo '#!/bin/bash
                  PERLLIB='"$HOME"'/po4a/lib '"$HOME"'/po4a/po4a "$@"' > $HOME/.local/bin/po4a
                  chmod +x $HOME/.local/bin/po4a
                  sudo apt install -y liblocale-gettext-perl libtext-wrapi18n-perl libunicode-linebreak-perl libtest-pod-perl libyaml-tiny-perl cpanminus gettext libsgmls-perl
                  cpanm Locale::gettext http://search.cpan.org/CPAN/authors/id/R/RA/RAAB/SGMLSpm-1.1.tar.gz Text::WrapI18N Unicode::GCString YAML::Tiny
                  cpanm -v --installdeps --notest $HOME/po4a
            - uses: actions/checkout@v3
            - name: Generate translations
              run: |
                  /bin/bash ./po4a.sh
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "chore: update translations"
                  git push
