name: Update translations

on:
    push:
        branches: [master]
        paths:
            - "source/**"
    pull_request:
        branches: [master]
        paths:
            - "source/**"
    workflow_dispatch:

jobs:
    translate:
        runs-on: ubuntu-latest
        steps:
            - name: Install po4a
              run: |
                  git clone --depth 1 https://github.com/mquinson/po4a $HOME/po4a
                  mkdir -p $HOME/.local/bin
                  echo '#!/bin/bash
                  PERLLIB='"$HOME"'/po4a/lib '"$HOME"'/po4a/po4a "$@"' > $HOME/.local/bin/po4a
                  chmod +x $HOME/.local/bin/po4a
                  sudo apt install -y liblocale-gettext-perl libtext-wrapi18n-perl libunicode-linebreak-perl libtest-pod-perl libyaml-tiny-perl cpanminus gettext libsgmls-perl
                  cpanm Locale::gettext http://search.cpan.org/CPAN/authors/id/R/RA/RAAB/SGMLSpm-1.1.tar.gz Text::WrapI18N Unicode::GCString YAML::Tiny
                  cpanm -v --installdeps --notest $HOME/po4a
            - uses: actions/checkout@v3
            - name: Generate translations
              run: /bin/bash ./po4a.sh
            - name: Push to current repo
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add -A
                  if ! git diff-index --quiet HEAD; then
                      git commit -m "chore: update translations"
                      git push
                  fi
            - name: Push to remote repos
              run: |
                  shopt -s nullglob
                  for dir in i18n/*/ ; do
                      dir=${dir%/}
                      repo=${dir#*/}
                      repo=${repo%/}
                      if [[ $repo != "titles" ]]; then
                          git clone --depth 1 https://PeterNjeim:${{ secrets.LIBRESCORE_TOKEN }}@github.com/LibreScore/$repo $HOME/$repo
                          mkdir -p $HOME/$repo/docs
                          cp -a $dir/* $HOME/$repo/docs/ -v
                          cp -a $dir/en/* $HOME/$repo/ -v
                          cd $HOME/$repo
                          git config user.name github-actions
                          git config user.email github-actions@github.com
                          git add -A
                          if ! git diff-index --quiet HEAD; then
                              git commit -m "chore: update translations"
                              git push
                          fi
                          cd $GITHUB_WORKSPACE
                          rm -R -f $HOME/$repo
                      fi
                  done
                  shopt -u nullglob
