name: Update translations

on:
    push:
        branches: [master]
        paths:
            - "source/**"
            - "po/**"
    pull_request:
        branches: [master]
        paths:
            - "source/**"
            - "po/**"
    # schedule:
    #     - cron: "*/15 * * * *"
    workflow_dispatch:

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    translate:
        runs-on: ubuntu-latest
        steps:
            - name: Install po4a
              run: |
                  git -C $HOME clone --single-branch --recurse-submodules --shallow-submodules --no-tags --depth=1 https://github.com/mquinson/po4a
                  mkdir -p $HOME/.local/bin
                  echo '#!/bin/bash
                  PERLLIB='"$HOME"'/po4a/lib '"$HOME"'/po4a/po4a "$@"' > $HOME/.local/bin/po4a
                  chmod +x $HOME/.local/bin/po4a
                  sudo apt install -y liblocale-gettext-perl libtext-wrapi18n-perl libunicode-linebreak-perl libtest-pod-perl libyaml-tiny-perl cpanminus gettext libsgmls-perl
                  cpanm Locale::gettext http://search.cpan.org/CPAN/authors/id/R/RA/RAAB/SGMLSpm-1.1.tar.gz Text::WrapI18N Unicode::GCString YAML::Tiny
                  cpanm -v --installdeps --notest $HOME/po4a
            - name: Fetch source files
              run:  |
                  mkdir $HOME/repos
                  curl -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/LibreScore/repos?per_page=100" | grep -e 'git_url*' | cut -d \" -f 4 | sed -e 's/^git:\/\//https:\/\/PeterNjeim:${{ secrets.LIBRESCORE_TOKEN }}@/g' | xargs -I {} bash -c "if ! [[ {} =~ /(LibreScore|pdfkit|mscz-parser|sf3|fonts).git$ ]]; then git -C $HOME/repos clone {} --single-branch --no-tags --depth=1 ; fi"
                  rm -R -f $HOME/repos/*/docs
                  find $HOME/repos -not -path "*/.git/*" ! -name "*.md" -type f -delete
                  find $HOME/repos/webmscore -not -path "./README.md" -delete
                  find $HOME/repos -type d -empty -delete
            - uses: actions/checkout@v3
            - name: Generate translations
              run: |
                  cp -a $HOME/repos/* source/ -v
                  /bin/bash ./po4a.sh
            - name: Push to current repo
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add -A
                  if git status -z --porcelain ./i18n; then
                      git commit -m "chore: update translations"
                      git push
                  else
                      curl -i -u PeterNjeim:${{ secrets.LIBRESCORE_TOKEN }} -d -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/LibreScore/docs/actions/runs/${{ github.run_id }}/cancel
                      curl -i -u PeterNjeim:${{ secrets.LIBRESCORE_TOKEN }} -X DELETE -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/LibreScore/docs/actions/runs/${{ github.run_id }}
                  fi
            - name: Push to remote repos
              run: |
                  shopt -s nullglob
                  for dir in i18n/*/ ; do
                      dir=${dir%/}
                      repo=${dir#*/}
                      repo=${repo%/}
                      if [[ $repo != "titles" ]]; then
                          mkdir -p $HOME/repos/$repo/docs
                          cp -a $dir/* $HOME/repos/$repo/docs/ -v
                          cp -a $dir/en/* $HOME/repos/$repo/ -v
                          cd $HOME/repos/$repo
                          git config user.name github-actions
                          git config user.email github-actions@github.com
                          git add -A
                          if git status -z --porcelain ./i18n; then
                              git commit -m "chore: update translations"
                              git push
                          fi
                          cd $GITHUB_WORKSPACE
                          rm -R -f $HOME/repos/$repo
                      fi
                  done
                  shopt -u nullglob
